export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ALL_PRODUCTS_FROM_CART = 'REMOVE_ALL_PRODUCTS_FROM_CART';
export const CHANGE_ATTRIBUTE = 'CHANGE_ATTRIBUTE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';

export const SET_CURRENCIES = 'SET_CURRENCIES';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';